name: Build the React App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      # Step 3: Navigate into the folder and install dependencies
      - name: Navigate and install dependencies
        working-directory: whisper-web-integration
        run: |
          npm install

      # Step 4: Build the React app
      - name: Build the React app
        working-directory: whisper-web-integration
        run: |
          npx vite build
          pwd
          ls -l

      # Step 5: Move build files to root
      - name: Move build files to root
        working-directory: whisper-web-integration
        run: |
          mv dist/* ../

      # Debug Step: List all files
      - name: Debug dist folder
        run: |
          echo "Contents of parent directory:"
          ls -l ../



      # Step 6: Commit and push the build files
      - name: Commit and push build files
        working-directory: whisper-web-integration
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add -f ../dist/ # Force-add the dist folder
          git commit -m "Add build files to dist [skip ci]"
          git push origin main # Replace 'main' with your target branch
